
      flowchart TD
          A(["Start"]) L_A_B_0@--> B{"Decision"}
          B --> C["Option A"] & D["Option B"]
          style C stroke-width:4px,stroke-dasharray: 5
          L_A_B_0@{ animation: slow }
          L_B_D_0@{ animation: fast }
