---
config:
  theme: "redux-dark-color"
---

  flowchart LR
    subgraph Outer
      subgraph InnerOne
        A[one] --> B[two]
      end
      subgraph InnerTwo
        C[three]
      end
    end
    subgraph Sibling
      D[four]
    end
    B --> C
    C --> D
