---
config:
  theme: "redux-dark"
---

  flowchart TB
    subgraph first[First]
      A[a] --> B[b]
    end
    subgraph second[Second]
      C[c]
    end
    second@{ view: collapsed }
    subgraph third[Third]
      D[d]
    end
    B --> C
    C --> D
