flowchart 
 n0@{ shape: div-rect, label: "div-rect" }
 n1@{ shape: div-proc, label: "div-proc" }
 n2@{ shape: divided-rectangle, label: "divided-rectangle" }
 n3@{ shape: divided-process, label: "divided-process" }
